installPath: C:\Program Files\Foundry Virtual Tabletop
dataPath: C:\Users\Example\AppData\Local\FoundryVTT\Data
currentPackageId: example-id
currentPackageType: World

#https://github.com/foundryvtt/foundryvtt-cli/blob/main/README.md