= Atuaro World Meta

== Scope of the World

KEEP TRACK OF WHY YOU’RE CREATING! Stay on track and make your world, campaign or novel the very best it can be! It all starts with a little motivation...

=== What is your motivation for building this world?
Decide what the world is being built for, and what it means to you - that way, it’ll be fit for purpose!

> To create a world where adventure can take place. To let players find their way in adventures that will be adapted to this world. A place where players can have fun, but perhaps their characters don't. With dark moments a la Ravenloft or Game of Thrones but with a renaissance flair and hope for a better future. Players will need to find adventure by exploring and interacting with the world.

=== What are you hoping to get out of it?
Knowing what you want from your world building project will help keep you on track when you get tired or stuck. Are you creating for a novel or a D&D campaign? What kind of experience do you want your audience to have?

> An open placeholder for adventure, by either designing an adventure, or by using written adventures and incorporating their story into this world. A world where players can create their path by finding adventure and interacting with the world. I am hoping to give my players an epic experience by combining the Gone Away War, Game of Thrones in the Assassins Creed world of Florence.

=== What is the Hook or Unique Selling Point of your world?
What makes it different? This is the core of your idea, the hook that draws you - and hopefully your players and readers - into the setting of the world. When we say “Unique” we really mean “special to you”. As long as you’re excited about the concept, that’s enough. Don’t feel like you have to reinvent the wheel and come up with something 100% original.

> A beautiful and bright renaissance world where each person can better themselves - on top of pile of death enemies.

== Theme of the World

Instill clarity and consistency to your storytelling. From the darkest dungeon to the brightest rainbow, choose the look and feel of your world, and how noble (or grim) your heroes’ fates will be!

=== What’s the Genre of your World?
Knowing the genre(s) and general technology/magic level will help you set expectations about your world, and keep your world feeling cohesive.

> A low magic but powerful renaissance sword & sorcery world where magic and gods exist and influence the world.

=== How does the world feel (player/reader experience)?
Do you want your world to feel mystical, or terrifying - or both? Should your audience be afraid or moved, filled with wanderlust or wonder? Awed by the past, or by the future? Your world will have a general feel to it, even if the specifics of tone vary from story to story.

> Atuaro should feel exciting and dangerous, with bright and dark experiences. A world where players need to worry about their environment. Most of the people in this world are only out to survive, those who can want to better themselves.

=== What is the character agency level like?
Character agency describes how much power the main characters or player characters have to change the world, and how long-lasting that change might be.

> The world should feel epic, so characters will be able to effect a great deal of change in the world, and that change might be long lasting. Because it can be a dark world too, that change won't always be good! Fumbling or making big mistakes will have consequences!

=== What is the tone of your world
Is your world  *dark* (e.g. Game of Thrones, Battlestar Galactica, The Witcher)  or *bright* (e.g. original Star Trek, the Princess bride, My Little Pony),  or *somewhere in the middle* (e.g. StarGate, Harry Potter, Shannara Chronicles)?  How pleasant or difficult is it to live there, in general? Do horrible or wondrous things happen to ordinary people?

> Atuaro is recovering from the Reckoning and is ending a golden age. A period of hope and prosperity that lasted during the last kings is ending. The once previously untouchable Houses are loosing power to the Guilds. Not all of ramifications of the Reckoning are gone. There are still plenty of creatures at the fringes of civilisation that liked it better when the lights were off and they are encroaching on civilisation.

=== What are the recurring themes
What themes reinforce the genre, tone and feel of your world? A few recurring themes can help anchor your audience in your tone and genre, and establish your hook. What three motifs/scenes/themes capture the world you’re trying to create? Give three to five examples.

These motifs are a great way to help reinforce the feeling of your world, despite the different pacing and mood of locations or scenes within your story or campaign. They do not need to feature in every single session or scene.

> . Reoccurring theme of things seeming fine on the surface but being corrupt beneath.
> . The golden age did not bring prosperity for all
> . Control vs Freedom is not Order vs Chaos

== Focus Points of the World

Focus the subjects you will be expanding on. *Choose three to five focal points of your world to focus your world building on*  It’s a sad truth of world building that you can’t create EVERYTHING! Decide a few focus points* you want to expand on. This will give the impression that your world is very deep and detailed. You can always expand more areas later!

*Examples might include (this list is not exhaustive!)*
-   Government Presence
-   Rule Of Law
-   Social Services
-   Economic Strength
-   Wealth Distribution
-   Agriculture And Trade
-   Race Relations
-   Class Relations
-   Gender Relations
-   Sexual Orientation Relations
-   Military Influence
-   Religious Influence
-   Technology Influence
-   Arts And Culture Influence

> . Control vs Freedom and Order vs Chaos.
> . Rule Of Law by Wealth, Military, and Religious Influence.
> . Technology, Arts, And Culture Influences the new world.
> . The fall of empire and those that want to stay in power.

== Drama Points of the World

Adding Drama is the way to put your world in motion. *Add 5 points of drama to your world.  *Drama is the current affairs of your world - what’s happening right now. You can use one or two of them for your main plot line, but the rest are just there to create the impression of a larger world in motion. Drama is a great source not only of side quests and B plots, but also of background dialogue! If you need to add more, use this expanded section.

> . Beauty and order. Or so it seems. Chaos still reigns beneath the veil.
> . Each faction and person vies for power. Those who don't fight for survival.
> . A renaissance world, think 15th century Italy but with magic. The moment you leave the cities it becomes a 14th century world.
> . The scourge made the world, which was already dog eat dog, even more dangerous.
> . The gods hate the fact that their are people who can use the weave and aether to perform acts of magic.
> . A rare medium named aether can power technological artfacts that wield great power!

Can you force the players into making practical, but morally questionable decisions, only to later contrast their choices against the selfless heroism of decent “common folk”? What price will they have to pay to save the city, and will their victory be complete or will it be a hollow one? What kinds of disputes will they encounter between factions, and what solutions will they find for them? A plague gives your players a chance to “save” a city, while at the same asking them what it means to be a hero.

== Basic World Properties

Describe your world's basic properties. Make your setting feel unique with strange geographical quirks, bizarre weather, and deep magic.

=== Rules of the World
What are the fundamental differences in the natural laws of your world compared to Earth?

Does your world have magic or altered gravity, midichlorians or psionics? Are the gods wandering the world? Nail down your world’s natural laws now - they will have fundamental repercussions on everything else in your world! *Make sure you sense-check with your previous answers - if your genre is hard sci-fi, you might not want to introduce magic, for example.

> *The World Is Ancient.* Empires rise and fall, leaving few places that have not been touched by imperial grandeur or decay. War, time, and natural forces eventually claim the mortal world, leaving it rich with places of adventure and mystery. Ancient civilisations and their knowledge survive in legends, magic items, and their ruins. Chaos and evil often follow an empire's collapse.

> *The World Is Magical.* Practitioners of magic are few in number, but they leave evidence of their craft everywhere. The higher the level of magic the fewer the practitioners. The magic can be as innocuous and commonplace as a potion that heals wounds to something much more rare and impressive, such as a levitating tower or a stone golem guarding the gates of a city. Beyond the realms of civilisation are caches of magic items guarded by magic traps, as well as magically constructed dungeons inhabited by monsters created by magic, cursed by magic, or endowed with magical abilities. Magic comes from The Weave. It is an energy field that connects everything and all.
> 
> *Note.* Artificers and the like talk to the DM, you will need to use aether.

> *Gods Oversee the World.* The gods are real and embody a variety of beliefs, with each god claiming dominion over an aspect of the world. Gods exert influence over the world by granting divine magic to their followers and sending signs and portents to guide them. The follower of a god serves as an agent of that god in the world. The agent seeks to further the ideals of that god and defeat its rivals. While some folk might refuse to honour the gods, none can deny their existence. Gods can't manifest themselves directly as they are incorporeal. Celestials (angels and demons) are the most used and known 'super'-agents for a deity. The more Faith a god receives the more powerfull his divinity and plentyfull celestials.

> *Source of magic.* The power granted to you by your patron (cleric, warlock) is not equal to being able to manipulate the weave or what is granted to you by the primal forces. Divine is religion, the weave is arcane, and primal are the forces of nature.

== How did this world come to be? (Cosmology)
The dominant religion, The Children of the Suns, believes that the world is the child of the twin suns, La and Tho. In reality, the world was intentionally created from a nebula by aliens who will be back to check on it someday... Write how your world ACTUALLY came to be - was it born from an egg, created by a god, or sneezed into being? You can add the prevalent in-world belief if you like. Just one paragraph on this - don't go full Silmarillion!

> The only allowed official religion is The Faith of Ohm. Although other gods exist, Ohm is the one and only official one on the continent where our adventures take place.  
> 
> * As clearly stated by Law, don't lightning the messenger please.
> 
> The dominant religion, The Faith of Ohm, believes that all creation - from the multiverse as a whole to the tiniest pebble or grain of sand - is a mysterious and beautiful sign pointing to Ohm's divine power. We are in the cradle and are the origin and most perfect of all its creations.
> 
> * Who knew humans could be so self-centered?

=== World Geography
What does the geography of your world look like?  Does your Geography have any special properties or features? This should be a generic vision of your geography. Is your world full of volcanoes and lava flows or floating islands? Is it an ice planet, or a desert waste? Is it a planet-city like Coruscant? Is it bio-diverse or all the same?

From winters which last decades (Game of Thrones, G.R.R. Martin) to moons which throw destructive spores (World of Pern, Anne MacCaffery), extraordinary geographical features can add character and challenges to your world. What are the fundamental truths of the physical geography of your world?

Remember to refer back to your genre, tone and motifs in your Foundation! They’ll give you a tonne of inspiration for this.

> The geology of the world is hugely varied and complex, and gives rise to the wide variety of landscapes found across the continent, from the Mountain Ranges and Highlands to the rolling plains and frozen tundra.

=== What is the initial size of your active setting?
What is the initial scale* of your active storytelling space? An island, a region or a continent, for example? Defining your initial active setting doesn’t mean your players or main characters can’t go elsewhere! But it does help you create a starting point which feels rich and alive. Remember this will be affected by the genre! If you’re playing a Star Trek campaign, you’ll be exploring different planets, so an active area might be a solar system or a cluster of systems.

> All adventures and campaigns take place in this world. The size of is as yet undefined. But the initial story starts in a small village named Kainga, near the city of Loukotokía, although everybody names it Anthill. Loukotokia could be regarded as Florence during the renaissance. A bustling city with entrepreneurial people and a flourishing trade and industry.

== People of the World

Explore the impact of sentience in your world. Breathe life into your world with great fallen empires, forgotten cities and lost civilisations. Add conflict and drama with the struggles and politics of today.

=== Who used to live here, and what’s their history?
Write max. 1 paragraph on each lost civilisation that was active in the area. Remember you can always add more later, which have not yet been discovered! This is where the unknown mysteries come from, and a great source of dungeons, secrets, adventures, unique items and more. Also makes your world feel living and established. If you want your world to feel brand new and unsettled, write instead about the geological history of your world - the fossils that people will find.

> The Akkadian are an ancient and highly-advanced species of humanoid beings who were active on what is now the Kingdom of Eden during the First Flowering. After their empire fell the Mauryan people rose to power and ruled for tens of thousands of years .After the Mauryan came the Helvetian. As the human cities grew and their borders ended, the Helvetian were the first and most vast human empire and were pivotal in the human expansion.  Now the last true king of the Helvetian's is dead the empire is hit hard by the Scourge the other races are reclaiming their place on Atuaro. 
> 
> From the original settler races here since the dawn of time, to the proud people and more recent humanoid races and evolutions. This paradise has an abundance of races in all sizes and colours. While the expanding human empires pushed them to the fringes, now that civilisation is crumbling they are claiming their rightful(?) place in the world.
> 
> The human nations are hungry for power, territory and resources but are ravished by the Scourge. The settler races, proud peoples, and many others were trying desperately to maintain their territories from human encroachment, as the human empires repeatedly try to seize their lands for expansion. Now the humans have lost the momentum...

== Appendix N

Stay inspired and focused, create an anchor to reinvigorate your passion. Inspiration, inspiration, inspiration! What movies, music, art and ideas have inspired your world setting?Collect all the different media references together here, to create a grand library of inspiration tailored to your world. Come back whenever you want to recapture the mood or get inspired for a new writing sprint!

Make sure you add notes to detail WHAT in each piece of media inspires you. Marking what you love about your references will help you when you come back later! For example, for a “treasure seeking amongst the stars” setting, you might add both “Indiana Jones” and “Star Trek”. You love the dungeon-delving aspect of Indiana Jones, but your world is more like Star Trek from a genre and technology standpoint.

* Terry Pratchett and Discworld
* George RR Martin and Game of Thrones
* Gone Away World by Nick Harckaway
* Florence and Rome in the Assassin Creed games
* Miracle of Sound
 
Different D&D channels on youtube.com a.o

* Matthew Colleville
* Dungeoncraft
* Bob the Worldbuilder
* and many others ...
